# Generated by Django 3.2.6 on 2021-08-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('password', models.CharField(default=None, max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1)),
            ],
        ),
    ]
