# Generated by Django 3.2.6 on 2021-08-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_location', models.CharField(default=None, max_length=32)),
                ('delivery_location', models.CharField(default=None, max_length=32)),
                ('status', models.CharField(choices=[('IT', 'In-Transit'), ('DE', 'Delivered')], max_length=32)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
