# Generated by Django 3.2.6 on 2021-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dispatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatches',
            name='status',
            field=models.CharField(choices=[('In Transit', 'In-Transit'), ('Delivered', 'Delivered')], max_length=32),
        ),
    ]
