# Generated by Django 3.2.6 on 2021-08-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dispatches_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='POD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dispatches')),
            ],
        ),
    ]
